language: objective-c
notifications:
  email: false
osx_image: xcode7.2
xcode_workspace: Tentacle.xcworkspace
xcode_scheme: Tentacle
script: xctool -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=
