language: objective-c
notifications:
  email: false
osx_image: xcode7.2
before_install:
  - brew update
  - brew upgrade carthage
before_script:
  - carthage bootstrap --use-submodules --no-build
xcode_workspace: Tentacle.xcworkspace
xcode_scheme:
 - Tentacle
 - TentacleiOS
 - update-test-fixtures
